// Generated by gen_regs.py on 2026-02-08 15:51:24.155995
/*
  Instantiation Template:

  reg_file reg_file_inst (
    .clk_i      (),
    .rst_ni     (),
    .addr_i     (),
    .wdata_i    (),
    .we_i       (),
    .rdata_o    (),
    .freq_lo_o  (),
    .freq_hi_o  (),
    .pw_lo_o    (),
    .pw_hi_o    (),
    .control_o  (),
    .ad_o       (),
    .sr_o       ()
  );
*/

module reg_file (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic [6:0]  addr_i,
    input  logic [7:0]  wdata_i,
    input  logic        we_i,
    output logic [7:0]  rdata_o,

    output logic [15:0][7:0] freq_lo_o,
    output logic [15:0][7:0] freq_hi_o,
    output logic [15:0][7:0] pw_lo_o,
    output logic [15:0][7:0] pw_hi_o,
    output logic [15:0][7:0] control_o,
    output logic [15:0][7:0] ad_o,
    output logic [15:0][7:0] sr_o
);

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            freq_lo_o[0] <= 8'h00;
            freq_lo_o[1] <= 8'h00;
            freq_lo_o[2] <= 8'h00;
            freq_lo_o[3] <= 8'h00;
            freq_lo_o[4] <= 8'h00;
            freq_lo_o[5] <= 8'h00;
            freq_lo_o[6] <= 8'h00;
            freq_lo_o[7] <= 8'h00;
            freq_lo_o[8] <= 8'h00;
            freq_lo_o[9] <= 8'h00;
            freq_lo_o[10] <= 8'h00;
            freq_lo_o[11] <= 8'h00;
            freq_lo_o[12] <= 8'h00;
            freq_lo_o[13] <= 8'h00;
            freq_lo_o[14] <= 8'h00;
            freq_lo_o[15] <= 8'h00;
            freq_hi_o[0] <= 8'h00;
            freq_hi_o[1] <= 8'h00;
            freq_hi_o[2] <= 8'h00;
            freq_hi_o[3] <= 8'h00;
            freq_hi_o[4] <= 8'h00;
            freq_hi_o[5] <= 8'h00;
            freq_hi_o[6] <= 8'h00;
            freq_hi_o[7] <= 8'h00;
            freq_hi_o[8] <= 8'h00;
            freq_hi_o[9] <= 8'h00;
            freq_hi_o[10] <= 8'h00;
            freq_hi_o[11] <= 8'h00;
            freq_hi_o[12] <= 8'h00;
            freq_hi_o[13] <= 8'h00;
            freq_hi_o[14] <= 8'h00;
            freq_hi_o[15] <= 8'h00;
            pw_lo_o[0] <= 8'h00;
            pw_lo_o[1] <= 8'h00;
            pw_lo_o[2] <= 8'h00;
            pw_lo_o[3] <= 8'h00;
            pw_lo_o[4] <= 8'h00;
            pw_lo_o[5] <= 8'h00;
            pw_lo_o[6] <= 8'h00;
            pw_lo_o[7] <= 8'h00;
            pw_lo_o[8] <= 8'h00;
            pw_lo_o[9] <= 8'h00;
            pw_lo_o[10] <= 8'h00;
            pw_lo_o[11] <= 8'h00;
            pw_lo_o[12] <= 8'h00;
            pw_lo_o[13] <= 8'h00;
            pw_lo_o[14] <= 8'h00;
            pw_lo_o[15] <= 8'h00;
            pw_hi_o[0] <= 8'h00;
            pw_hi_o[1] <= 8'h00;
            pw_hi_o[2] <= 8'h00;
            pw_hi_o[3] <= 8'h00;
            pw_hi_o[4] <= 8'h00;
            pw_hi_o[5] <= 8'h00;
            pw_hi_o[6] <= 8'h00;
            pw_hi_o[7] <= 8'h00;
            pw_hi_o[8] <= 8'h00;
            pw_hi_o[9] <= 8'h00;
            pw_hi_o[10] <= 8'h00;
            pw_hi_o[11] <= 8'h00;
            pw_hi_o[12] <= 8'h00;
            pw_hi_o[13] <= 8'h00;
            pw_hi_o[14] <= 8'h00;
            pw_hi_o[15] <= 8'h00;
            control_o[0] <= 8'h00;
            control_o[1] <= 8'h00;
            control_o[2] <= 8'h00;
            control_o[3] <= 8'h00;
            control_o[4] <= 8'h00;
            control_o[5] <= 8'h00;
            control_o[6] <= 8'h00;
            control_o[7] <= 8'h00;
            control_o[8] <= 8'h00;
            control_o[9] <= 8'h00;
            control_o[10] <= 8'h00;
            control_o[11] <= 8'h00;
            control_o[12] <= 8'h00;
            control_o[13] <= 8'h00;
            control_o[14] <= 8'h00;
            control_o[15] <= 8'h00;
            ad_o[0] <= 8'h00;
            ad_o[1] <= 8'h00;
            ad_o[2] <= 8'h00;
            ad_o[3] <= 8'h00;
            ad_o[4] <= 8'h00;
            ad_o[5] <= 8'h00;
            ad_o[6] <= 8'h00;
            ad_o[7] <= 8'h00;
            ad_o[8] <= 8'h00;
            ad_o[9] <= 8'h00;
            ad_o[10] <= 8'h00;
            ad_o[11] <= 8'h00;
            ad_o[12] <= 8'h00;
            ad_o[13] <= 8'h00;
            ad_o[14] <= 8'h00;
            ad_o[15] <= 8'h00;
            sr_o[0] <= 8'h00;
            sr_o[1] <= 8'h00;
            sr_o[2] <= 8'h00;
            sr_o[3] <= 8'h00;
            sr_o[4] <= 8'h00;
            sr_o[5] <= 8'h00;
            sr_o[6] <= 8'h00;
            sr_o[7] <= 8'h00;
            sr_o[8] <= 8'h00;
            sr_o[9] <= 8'h00;
            sr_o[10] <= 8'h00;
            sr_o[11] <= 8'h00;
            sr_o[12] <= 8'h00;
            sr_o[13] <= 8'h00;
            sr_o[14] <= 8'h00;
            sr_o[15] <= 8'h00;
        end else if (we_i) begin
            case (addr_i)
                7'h00: freq_lo_o[0] <= wdata_i;
                7'h01: freq_hi_o[0] <= wdata_i;
                7'h02: pw_lo_o[0] <= wdata_i;
                7'h03: pw_hi_o[0] <= wdata_i;
                7'h04: control_o[0] <= wdata_i;
                7'h05: ad_o[0] <= wdata_i;
                7'h06: sr_o[0] <= wdata_i;
                7'h07: freq_lo_o[1] <= wdata_i;
                7'h08: freq_hi_o[1] <= wdata_i;
                7'h09: pw_lo_o[1] <= wdata_i;
                7'h0A: pw_hi_o[1] <= wdata_i;
                7'h0B: control_o[1] <= wdata_i;
                7'h0C: ad_o[1] <= wdata_i;
                7'h0D: sr_o[1] <= wdata_i;
                7'h0E: freq_lo_o[2] <= wdata_i;
                7'h0F: freq_hi_o[2] <= wdata_i;
                7'h10: pw_lo_o[2] <= wdata_i;
                7'h11: pw_hi_o[2] <= wdata_i;
                7'h12: control_o[2] <= wdata_i;
                7'h13: ad_o[2] <= wdata_i;
                7'h14: sr_o[2] <= wdata_i;
                7'h15: freq_lo_o[3] <= wdata_i;
                7'h16: freq_hi_o[3] <= wdata_i;
                7'h17: pw_lo_o[3] <= wdata_i;
                7'h18: pw_hi_o[3] <= wdata_i;
                7'h19: control_o[3] <= wdata_i;
                7'h1A: ad_o[3] <= wdata_i;
                7'h1B: sr_o[3] <= wdata_i;
                7'h1C: freq_lo_o[4] <= wdata_i;
                7'h1D: freq_hi_o[4] <= wdata_i;
                7'h1E: pw_lo_o[4] <= wdata_i;
                7'h1F: pw_hi_o[4] <= wdata_i;
                7'h20: control_o[4] <= wdata_i;
                7'h21: ad_o[4] <= wdata_i;
                7'h22: sr_o[4] <= wdata_i;
                7'h23: freq_lo_o[5] <= wdata_i;
                7'h24: freq_hi_o[5] <= wdata_i;
                7'h25: pw_lo_o[5] <= wdata_i;
                7'h26: pw_hi_o[5] <= wdata_i;
                7'h27: control_o[5] <= wdata_i;
                7'h28: ad_o[5] <= wdata_i;
                7'h29: sr_o[5] <= wdata_i;
                7'h2A: freq_lo_o[6] <= wdata_i;
                7'h2B: freq_hi_o[6] <= wdata_i;
                7'h2C: pw_lo_o[6] <= wdata_i;
                7'h2D: pw_hi_o[6] <= wdata_i;
                7'h2E: control_o[6] <= wdata_i;
                7'h2F: ad_o[6] <= wdata_i;
                7'h30: sr_o[6] <= wdata_i;
                7'h31: freq_lo_o[7] <= wdata_i;
                7'h32: freq_hi_o[7] <= wdata_i;
                7'h33: pw_lo_o[7] <= wdata_i;
                7'h34: pw_hi_o[7] <= wdata_i;
                7'h35: control_o[7] <= wdata_i;
                7'h36: ad_o[7] <= wdata_i;
                7'h37: sr_o[7] <= wdata_i;
                7'h38: freq_lo_o[8] <= wdata_i;
                7'h39: freq_hi_o[8] <= wdata_i;
                7'h3A: pw_lo_o[8] <= wdata_i;
                7'h3B: pw_hi_o[8] <= wdata_i;
                7'h3C: control_o[8] <= wdata_i;
                7'h3D: ad_o[8] <= wdata_i;
                7'h3E: sr_o[8] <= wdata_i;
                7'h3F: freq_lo_o[9] <= wdata_i;
                7'h40: freq_hi_o[9] <= wdata_i;
                7'h41: pw_lo_o[9] <= wdata_i;
                7'h42: pw_hi_o[9] <= wdata_i;
                7'h43: control_o[9] <= wdata_i;
                7'h44: ad_o[9] <= wdata_i;
                7'h45: sr_o[9] <= wdata_i;
                7'h46: freq_lo_o[10] <= wdata_i;
                7'h47: freq_hi_o[10] <= wdata_i;
                7'h48: pw_lo_o[10] <= wdata_i;
                7'h49: pw_hi_o[10] <= wdata_i;
                7'h4A: control_o[10] <= wdata_i;
                7'h4B: ad_o[10] <= wdata_i;
                7'h4C: sr_o[10] <= wdata_i;
                7'h4D: freq_lo_o[11] <= wdata_i;
                7'h4E: freq_hi_o[11] <= wdata_i;
                7'h4F: pw_lo_o[11] <= wdata_i;
                7'h50: pw_hi_o[11] <= wdata_i;
                7'h51: control_o[11] <= wdata_i;
                7'h52: ad_o[11] <= wdata_i;
                7'h53: sr_o[11] <= wdata_i;
                7'h54: freq_lo_o[12] <= wdata_i;
                7'h55: freq_hi_o[12] <= wdata_i;
                7'h56: pw_lo_o[12] <= wdata_i;
                7'h57: pw_hi_o[12] <= wdata_i;
                7'h58: control_o[12] <= wdata_i;
                7'h59: ad_o[12] <= wdata_i;
                7'h5A: sr_o[12] <= wdata_i;
                7'h5B: freq_lo_o[13] <= wdata_i;
                7'h5C: freq_hi_o[13] <= wdata_i;
                7'h5D: pw_lo_o[13] <= wdata_i;
                7'h5E: pw_hi_o[13] <= wdata_i;
                7'h5F: control_o[13] <= wdata_i;
                7'h60: ad_o[13] <= wdata_i;
                7'h61: sr_o[13] <= wdata_i;
                7'h62: freq_lo_o[14] <= wdata_i;
                7'h63: freq_hi_o[14] <= wdata_i;
                7'h64: pw_lo_o[14] <= wdata_i;
                7'h65: pw_hi_o[14] <= wdata_i;
                7'h66: control_o[14] <= wdata_i;
                7'h67: ad_o[14] <= wdata_i;
                7'h68: sr_o[14] <= wdata_i;
                7'h69: freq_lo_o[15] <= wdata_i;
                7'h6A: freq_hi_o[15] <= wdata_i;
                7'h6B: pw_lo_o[15] <= wdata_i;
                7'h6C: pw_hi_o[15] <= wdata_i;
                7'h6D: control_o[15] <= wdata_i;
                7'h6E: ad_o[15] <= wdata_i;
                7'h6F: sr_o[15] <= wdata_i;
                default: ;
            endcase
        end
    end

    always_comb begin
        case (addr_i)
            7'h00: rdata_o = freq_lo_o[0];
            7'h01: rdata_o = freq_hi_o[0];
            7'h02: rdata_o = pw_lo_o[0];
            7'h03: rdata_o = pw_hi_o[0];
            7'h04: rdata_o = control_o[0];
            7'h05: rdata_o = ad_o[0];
            7'h06: rdata_o = sr_o[0];
            7'h07: rdata_o = freq_lo_o[1];
            7'h08: rdata_o = freq_hi_o[1];
            7'h09: rdata_o = pw_lo_o[1];
            7'h0A: rdata_o = pw_hi_o[1];
            7'h0B: rdata_o = control_o[1];
            7'h0C: rdata_o = ad_o[1];
            7'h0D: rdata_o = sr_o[1];
            7'h0E: rdata_o = freq_lo_o[2];
            7'h0F: rdata_o = freq_hi_o[2];
            7'h10: rdata_o = pw_lo_o[2];
            7'h11: rdata_o = pw_hi_o[2];
            7'h12: rdata_o = control_o[2];
            7'h13: rdata_o = ad_o[2];
            7'h14: rdata_o = sr_o[2];
            7'h15: rdata_o = freq_lo_o[3];
            7'h16: rdata_o = freq_hi_o[3];
            7'h17: rdata_o = pw_lo_o[3];
            7'h18: rdata_o = pw_hi_o[3];
            7'h19: rdata_o = control_o[3];
            7'h1A: rdata_o = ad_o[3];
            7'h1B: rdata_o = sr_o[3];
            7'h1C: rdata_o = freq_lo_o[4];
            7'h1D: rdata_o = freq_hi_o[4];
            7'h1E: rdata_o = pw_lo_o[4];
            7'h1F: rdata_o = pw_hi_o[4];
            7'h20: rdata_o = control_o[4];
            7'h21: rdata_o = ad_o[4];
            7'h22: rdata_o = sr_o[4];
            7'h23: rdata_o = freq_lo_o[5];
            7'h24: rdata_o = freq_hi_o[5];
            7'h25: rdata_o = pw_lo_o[5];
            7'h26: rdata_o = pw_hi_o[5];
            7'h27: rdata_o = control_o[5];
            7'h28: rdata_o = ad_o[5];
            7'h29: rdata_o = sr_o[5];
            7'h2A: rdata_o = freq_lo_o[6];
            7'h2B: rdata_o = freq_hi_o[6];
            7'h2C: rdata_o = pw_lo_o[6];
            7'h2D: rdata_o = pw_hi_o[6];
            7'h2E: rdata_o = control_o[6];
            7'h2F: rdata_o = ad_o[6];
            7'h30: rdata_o = sr_o[6];
            7'h31: rdata_o = freq_lo_o[7];
            7'h32: rdata_o = freq_hi_o[7];
            7'h33: rdata_o = pw_lo_o[7];
            7'h34: rdata_o = pw_hi_o[7];
            7'h35: rdata_o = control_o[7];
            7'h36: rdata_o = ad_o[7];
            7'h37: rdata_o = sr_o[7];
            7'h38: rdata_o = freq_lo_o[8];
            7'h39: rdata_o = freq_hi_o[8];
            7'h3A: rdata_o = pw_lo_o[8];
            7'h3B: rdata_o = pw_hi_o[8];
            7'h3C: rdata_o = control_o[8];
            7'h3D: rdata_o = ad_o[8];
            7'h3E: rdata_o = sr_o[8];
            7'h3F: rdata_o = freq_lo_o[9];
            7'h40: rdata_o = freq_hi_o[9];
            7'h41: rdata_o = pw_lo_o[9];
            7'h42: rdata_o = pw_hi_o[9];
            7'h43: rdata_o = control_o[9];
            7'h44: rdata_o = ad_o[9];
            7'h45: rdata_o = sr_o[9];
            7'h46: rdata_o = freq_lo_o[10];
            7'h47: rdata_o = freq_hi_o[10];
            7'h48: rdata_o = pw_lo_o[10];
            7'h49: rdata_o = pw_hi_o[10];
            7'h4A: rdata_o = control_o[10];
            7'h4B: rdata_o = ad_o[10];
            7'h4C: rdata_o = sr_o[10];
            7'h4D: rdata_o = freq_lo_o[11];
            7'h4E: rdata_o = freq_hi_o[11];
            7'h4F: rdata_o = pw_lo_o[11];
            7'h50: rdata_o = pw_hi_o[11];
            7'h51: rdata_o = control_o[11];
            7'h52: rdata_o = ad_o[11];
            7'h53: rdata_o = sr_o[11];
            7'h54: rdata_o = freq_lo_o[12];
            7'h55: rdata_o = freq_hi_o[12];
            7'h56: rdata_o = pw_lo_o[12];
            7'h57: rdata_o = pw_hi_o[12];
            7'h58: rdata_o = control_o[12];
            7'h59: rdata_o = ad_o[12];
            7'h5A: rdata_o = sr_o[12];
            7'h5B: rdata_o = freq_lo_o[13];
            7'h5C: rdata_o = freq_hi_o[13];
            7'h5D: rdata_o = pw_lo_o[13];
            7'h5E: rdata_o = pw_hi_o[13];
            7'h5F: rdata_o = control_o[13];
            7'h60: rdata_o = ad_o[13];
            7'h61: rdata_o = sr_o[13];
            7'h62: rdata_o = freq_lo_o[14];
            7'h63: rdata_o = freq_hi_o[14];
            7'h64: rdata_o = pw_lo_o[14];
            7'h65: rdata_o = pw_hi_o[14];
            7'h66: rdata_o = control_o[14];
            7'h67: rdata_o = ad_o[14];
            7'h68: rdata_o = sr_o[14];
            7'h69: rdata_o = freq_lo_o[15];
            7'h6A: rdata_o = freq_hi_o[15];
            7'h6B: rdata_o = pw_lo_o[15];
            7'h6C: rdata_o = pw_hi_o[15];
            7'h6D: rdata_o = control_o[15];
            7'h6E: rdata_o = ad_o[15];
            7'h6F: rdata_o = sr_o[15];
            default: rdata_o = 8'h00;
        endcase
    end

endmodule
