// Generated by gen_regs.py on 2026-02-09 15:24:42.367191
/*
  Instantiation Template:

  reg_file reg_file_inst (
    .clk_i      (),
    .rst_ni     (),
    .addr_i     (),
    .wdata_i    (),
    .we_i       (),
    .rdata_o    (),
    .freq_lo_o  (),
    .freq_hi_o  (),
    .pw_lo_o    (),
    .pw_hi_o    (),
    .control_o  (),
    .ad_o       (),
    .sr_o       ()
  );
*/

module reg_file (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic [6:0]  addr_i,
    input  logic [7:0]  wdata_i,
    input  logic        we_i,
    output logic [7:0]  rdata_o,

    output logic [2:0][7:0] freq_lo_o,
    output logic [2:0][7:0] freq_hi_o,
    output logic [2:0][7:0] pw_lo_o,
    output logic [2:0][7:0] pw_hi_o,
    output logic [2:0][7:0] control_o,
    output logic [2:0][7:0] ad_o,
    output logic [2:0][7:0] sr_o
);

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            freq_lo_o[0] <= 8'h00;
            freq_lo_o[1] <= 8'h00;
            freq_lo_o[2] <= 8'h00;
            freq_hi_o[0] <= 8'h00;
            freq_hi_o[1] <= 8'h00;
            freq_hi_o[2] <= 8'h00;
            pw_lo_o[0] <= 8'h00;
            pw_lo_o[1] <= 8'h00;
            pw_lo_o[2] <= 8'h00;
            pw_hi_o[0] <= 8'h00;
            pw_hi_o[1] <= 8'h00;
            pw_hi_o[2] <= 8'h00;
            control_o[0] <= 8'h00;
            control_o[1] <= 8'h00;
            control_o[2] <= 8'h00;
            ad_o[0] <= 8'h00;
            ad_o[1] <= 8'h00;
            ad_o[2] <= 8'h00;
            sr_o[0] <= 8'h00;
            sr_o[1] <= 8'h00;
            sr_o[2] <= 8'h00;
        end else if (we_i) begin
            case (addr_i)
                7'h00: freq_lo_o[0] <= wdata_i;
                7'h01: freq_hi_o[0] <= wdata_i;
                7'h02: pw_lo_o[0] <= wdata_i;
                7'h03: pw_hi_o[0] <= wdata_i;
                7'h04: control_o[0] <= wdata_i;
                7'h05: ad_o[0] <= wdata_i;
                7'h06: sr_o[0] <= wdata_i;
                7'h07: freq_lo_o[1] <= wdata_i;
                7'h08: freq_hi_o[1] <= wdata_i;
                7'h09: pw_lo_o[1] <= wdata_i;
                7'h0A: pw_hi_o[1] <= wdata_i;
                7'h0B: control_o[1] <= wdata_i;
                7'h0C: ad_o[1] <= wdata_i;
                7'h0D: sr_o[1] <= wdata_i;
                7'h0E: freq_lo_o[2] <= wdata_i;
                7'h0F: freq_hi_o[2] <= wdata_i;
                7'h10: pw_lo_o[2] <= wdata_i;
                7'h11: pw_hi_o[2] <= wdata_i;
                7'h12: control_o[2] <= wdata_i;
                7'h13: ad_o[2] <= wdata_i;
                7'h14: sr_o[2] <= wdata_i;
                default: ;
            endcase
        end
    end

    always_comb begin
        case (addr_i)
            7'h00: rdata_o = freq_lo_o[0];
            7'h01: rdata_o = freq_hi_o[0];
            7'h02: rdata_o = pw_lo_o[0];
            7'h03: rdata_o = pw_hi_o[0];
            7'h04: rdata_o = control_o[0];
            7'h05: rdata_o = ad_o[0];
            7'h06: rdata_o = sr_o[0];
            7'h07: rdata_o = freq_lo_o[1];
            7'h08: rdata_o = freq_hi_o[1];
            7'h09: rdata_o = pw_lo_o[1];
            7'h0A: rdata_o = pw_hi_o[1];
            7'h0B: rdata_o = control_o[1];
            7'h0C: rdata_o = ad_o[1];
            7'h0D: rdata_o = sr_o[1];
            7'h0E: rdata_o = freq_lo_o[2];
            7'h0F: rdata_o = freq_hi_o[2];
            7'h10: rdata_o = pw_lo_o[2];
            7'h11: rdata_o = pw_hi_o[2];
            7'h12: rdata_o = control_o[2];
            7'h13: rdata_o = ad_o[2];
            7'h14: rdata_o = sr_o[2];
            default: rdata_o = 8'h00;
        endcase
    end

endmodule
